require("core.plugin_configs.gruvbox")
require("core.plugin_configs.lualine")
require("core.plugin_configs.nvim-tree")
require("core.plugin_configs.telescope")
require("core.plugin_configs.treesitter")
require("core.plugin_configs.completion")
require("core.plugin_configs.lsp_config")
require("core.plugin_configs.lazy_git")
require("core.plugin_configs.lsp_lines")

