require("core.plugin_configs.gruvbox")
require("core.plugin_configs.lualine")
require("core.plugin_configs.nvim-tree")
require("core.plugin_configs.telescope")
require("core.plugin_configs.treesitter")
